#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CORE_DIR="$ROOT_DIR/InsightifyCore"

log() {
  printf '[reset-dev-data] %s\n' "$*"
}

remove_path() {
  local target="$1"
  if [ -e "$target" ]; then
    rm -rf "$target"
    log "removed: $target"
  else
    log "skip (not found): $target"
  fi
}

log "reset start"

# Remove local runtime data generated by Core.
remove_path "$CORE_DIR/logs"
remove_path "$CORE_DIR/tmp"
remove_path "$CORE_DIR/artifacts"

mkdir -p "$CORE_DIR/logs" "$CORE_DIR/tmp" "$CORE_DIR/artifacts"
log "recreated empty runtime dirs under InsightifyCore"

# Reset docker-backed persistence when Docker is available.
if command -v docker >/dev/null 2>&1; then
  if docker compose version >/dev/null 2>&1; then
    log "docker compose down -v postgres pgadmin minio"
    (
      cd "$ROOT_DIR"
      docker compose down -v postgres pgadmin minio || true
    )
  else
    log "docker compose unavailable; skipped volume reset"
  fi
else
  log "docker unavailable; skipped volume reset"
fi

cat <<'MSG'
[reset-dev-data] Browser localStorage is not removable from this shell.
Run this once in browser DevTools Console on InsightifyWeb:
Object.keys(localStorage)
  .filter((k) => k.startsWith('insightify.'))
  .forEach((k) => localStorage.removeItem(k));
MSG

log "reset done"
