import { createDefaultGraphLayout, parseFlowGraph, type FlowGraph, type GeneratedFlowGraph } from "@insightify/graph-domain";

// Rich multi-cloud & multi-kind architectural fixture with diverse API endpoints
const source: FlowGraph = {
  title: "NovaFlow Architecture",
  summary:
    "Full-stack AI workflow orchestration platform spanning Web, APIs, Microservices, Cloud Stores, and AI Agents.",
  nodes: [
    // --- Root Level Nodes ---
    {
      id: "frontend-portal",
      title: "Frontend Applications",
      summary: "Modern React web console and native mobile apps connecting to the platform.",
      kind: "room",
      technology: "React",
      parentId: null,
      evidence: ["apps/web/src/App.tsx", "apps/mobile/src/index.ts"],
      tags: ["frontend", "react", "spa"],
      status: "ready",
      codeSnippet: "export function DashboardApp(): React.JSX.Element",
    },
    {
      id: "api-gateway",
      title: "API Gateway Router",
      summary: "High-throughput reverse proxy, SSL termination, and endpoint dispatcher.",
      kind: "room",
      technology: "REST",
      parentId: null,
      evidence: ["services/gateway/src/server.ts"],
      tags: ["gateway", "rest", "graphql", "routing"],
      status: "ready",
      codeSnippet: "export const app = fastify({ logger: true });\nawait app.register(routes);",
    },
    {
      id: "auth-guard",
      title: "Identity & JWT Guard",
      summary: "Zero-trust session verification, OAuth2 tokens, and role-based access control.",
      kind: "auth",
      technology: "OAuth",
      parentId: null,
      evidence: ["services/auth/src/guard.ts"],
      tags: ["security", "guard", "jwt", "rbac"],
      status: "ready",
      codeSnippet: "export async function verifySession(token: string): Promise<SessionUser>",
    },
    {
      id: "workflow-engine",
      title: "Workflow Engine",
      summary: "Distributed workflow scheduler and stateful execution pipeline.",
      kind: "room",
      technology: "Docker",
      parentId: null,
      evidence: ["services/engine/src/coordinator.ts"],
      tags: ["engine", "orchestration", "docker"],
      status: "ready",
      codeSnippet: "export class WorkflowCoordinator implements PipelineScheduler",
    },
    {
      id: "event-bus",
      title: "Event Bus & Task Queue",
      summary: "Low-latency Redis streams buffering asynchronous graph execution tasks.",
      kind: "queue",
      technology: "Redis",
      parentId: null,
      evidence: ["packages/queue/src/redis.ts"],
      tags: ["redis", "pubsub", "async", "streaming"],
      status: "working",
      codeSnippet: "export const taskStream = new RedisStream('events:workflow:v1');",
    },
    {
      id: "primary-db",
      title: "PostgreSQL Database",
      summary: "ACID persistent storage for workflow definitions, users, and audit logs.",
      kind: "database",
      technology: "PostgreSQL",
      parentId: null,
      evidence: ["packages/db/schema.sql"],
      tags: ["postgres", "rdbms", "acid", "persistence"],
      status: "ready",
      codeSnippet: "CREATE TABLE workflows (\n  id UUID PRIMARY KEY,\n  user_id UUID NOT NULL,\n  status VARCHAR(32) NOT NULL\n);",
    },
    {
      id: "ai-synthesizer",
      title: "OpenAI Synthesizer",
      summary: "Generative intelligence agent generating code transforms and structural summaries.",
      kind: "external",
      technology: "OpenAI",
      parentId: null,
      evidence: ["services/ai/src/openai.ts"],
      tags: ["openai", "llm", "agent", "gpt-4o"],
      status: "working",
      codeSnippet: "const res = await openai.chat.completions.create({\n  model: 'gpt-4o',\n  messages: prompt\n});",
    },
    {
      id: "cloud-storage",
      title: "AWS S3 Asset Vault",
      summary: "Encrypted blob storage for repository tarballs, sandbox diffs, and artifacts.",
      kind: "external",
      technology: "AWS",
      parentId: null,
      evidence: ["services/storage/src/s3.ts"],
      tags: ["aws", "s3", "blob", "storage"],
      status: "ready",
      codeSnippet: "await s3.send(new PutObjectCommand({ Bucket: 'novaflow-vault', Key: path }));",
    },
    {
      id: "payment-hub",
      title: "Stripe Billing Hub",
      summary: "Subscription metering, customer portal, and invoice webhook handling.",
      kind: "external",
      technology: "Stripe",
      parentId: null,
      evidence: ["services/billing/src/stripe.ts"],
      tags: ["stripe", "billing", "webhook"],
      status: "ready",
      codeSnippet: "const session = await stripe.checkout.sessions.create({ mode: 'subscription' });",
    },
    {
      id: "analytics-lake",
      title: "GCP BigQuery Lake",
      summary: "Real-time telemetry and aggregated system performance metrics stream.",
      kind: "external",
      technology: "GCP",
      parentId: null,
      evidence: ["services/telemetry/src/bigquery.ts"],
      tags: ["gcp", "bigquery", "analytics", "cloud-run"],
      status: "ready",
      codeSnippet: "await bigquery.dataset('telemetry').table('events').insert(eventBatch);",
    },

    // --- API Gateway Nested Endpoints ---
    {
      id: "api-auth-login",
      title: "POST /api/v1/auth/login",
      summary: "User password & OAuth token exchange returning signed JWT access and refresh tokens.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/auth.ts"],
      tags: ["auth", "login", "jwt", "rate-limited"],
      status: "ready",
      codeSnippet: "router.post('/login', validate(LoginSchema), async (req, reply) => {\n  const token = await authenticateUser(req.body);\n  return reply.send({ token });\n});",
    },
    {
      id: "api-workflows-get",
      title: "GET /api/v1/workflows/:id",
      summary: "Fetches compiled workflow graph topology, step execution logs, and output state.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/workflows.ts"],
      tags: ["workflow", "read", "cache-control"],
      status: "ready",
      codeSnippet: "router.get('/:id', async (req, reply) => {\n  const flow = await db.workflows.findById(req.params.id);\n  return flow ? reply.send(flow) : reply.status(404).send();\n});",
    },
    {
      id: "api-workflows-create",
      title: "POST /api/v1/workflows",
      summary: "Validates workflow schema and stores new workflow definition in PostgreSQL.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/workflows.ts"],
      tags: ["workflow", "create", "validation"],
      status: "ready",
      codeSnippet: "router.post('/', authGuard, async (req, reply) => {\n  const workflow = await createWorkflow(req.user.id, req.body);\n  return reply.status(201).send(workflow);\n});",
    },
    {
      id: "api-workflows-run",
      title: "POST /api/v1/workflows/:id/execute",
      summary: "Enqueues execution job to Redis stream and returns run tracker ID for SSE streaming.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/execute.ts"],
      tags: ["execute", "async", "redis-stream"],
      status: "ready",
      codeSnippet: "router.post('/:id/execute', async (req, reply) => {\n  const runId = await queue.add('workflow-run', { id: req.params.id });\n  return reply.send({ runId });\n});",
    },
    {
      id: "api-ai-synthesize",
      title: "POST /api/v1/ai/synthesize",
      summary: "Streams LLM code decomposition and architectural graph generation in real-time.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/ai.ts"],
      tags: ["openai", "sse", "stream", "ai"],
      status: "working",
      codeSnippet: "router.post('/synthesize', async (req, reply) => {\n  reply.raw.setHeader('Content-Type', 'text/event-stream');\n  await streamAiTokens(req.body.prompt, reply.raw);\n});",
    },
    {
      id: "api-stripe-webhook",
      title: "POST /api/v1/webhooks/stripe",
      summary: "Verifies Stripe HMAC signature and processes checkout.session.completed events.",
      kind: "api",
      technology: "REST",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/routes/webhooks.ts"],
      tags: ["webhook", "stripe", "hmac-signed"],
      status: "ready",
      codeSnippet: "router.post('/stripe', rawBodyParser, async (req, reply) => {\n  const event = stripe.webhooks.constructEvent(req.rawBody, req.headers['stripe-signature'], secret);\n  await handleBillingEvent(event);\n  return reply.send({ received: true });\n});",
    },
    {
      id: "api-graphql",
      title: "POST /graphql",
      summary: "Unified GraphQL endpoint with schema stitching for client queries and subscriptions.",
      kind: "api",
      technology: "GraphQL",
      parentId: "api-gateway",
      evidence: ["services/gateway/src/graphql/schema.ts"],
      tags: ["graphql", "federation", "apollo"],
      status: "ready",
      codeSnippet: "export const server = new ApolloServer({\n  typeDefs,\n  resolvers,\n  introspection: true\n});",
    },

    // --- Frontend Portal Nested Nodes ---
    {
      id: "web-dashboard",
      title: "Web Dashboard UI",
      summary: "Interactive single-page application built with React and TailwindCSS.",
      kind: "ui",
      technology: "React",
      parentId: "frontend-portal",
      evidence: ["apps/web/src/pages/Dashboard.tsx"],
      tags: ["ui", "react", "dashboard"],
      status: "ready",
    },
    {
      id: "canvas-editor",
      title: "Visual Flow Canvas",
      summary: "High-performance SVG canvas rendering dynamic node topologies.",
      kind: "ui",
      technology: "React",
      parentId: "frontend-portal",
      evidence: ["apps/web/src/components/Canvas.tsx"],
      tags: ["canvas", "svg", "flowfold"],
      status: "ready",
    },
    {
      id: "mobile-client",
      title: "Mobile App View",
      summary: "Companion mobile application for notifications and status monitoring.",
      kind: "ui",
      technology: "React",
      parentId: "frontend-portal",
      evidence: ["apps/mobile/src/App.tsx"],
      tags: ["mobile", "react-native"],
      status: "ready",
    },
    {
      id: "auth-modal",
      title: "Auth Modal Screen",
      summary: "Login, SSO, and MFA verification screen overlay.",
      kind: "ui",
      technology: "React",
      parentId: "frontend-portal",
      evidence: ["apps/web/src/components/AuthModal.tsx"],
      tags: ["modal", "auth", "sso"],
      status: "ready",
    },

    // --- Workflow Engine Nested Nodes ---
    {
      id: "dispatch-service",
      title: "Step Dispatcher",
      summary: "Pulls pending workflow steps from Redis and allocates worker pods.",
      kind: "service",
      technology: "Docker",
      parentId: "workflow-engine",
      evidence: ["services/engine/src/dispatcher.ts"],
      tags: ["dispatcher", "worker"],
      status: "ready",
    },
    {
      id: "branch-evaluator",
      title: "Condition Branching",
      summary: "Evaluates conditional branches, validation rules, and error recovery policies.",
      kind: "decision",
      technology: "Docker",
      parentId: "workflow-engine",
      evidence: ["services/engine/src/evaluator.ts"],
      tags: ["decision", "branching", "rules"],
      status: "ready",
    },
    {
      id: "k8s-runner",
      title: "Kubernetes Pod Runner",
      summary: "Spawns isolated container jobs for CPU-intensive compilation and linting.",
      kind: "service",
      technology: "Kubernetes",
      parentId: "workflow-engine",
      evidence: ["services/engine/src/k8s.ts"],
      tags: ["k8s", "containers", "sandbox"],
      status: "ready",
    },
    {
      id: "state-checkpoint",
      title: "Checkpoint Logger",
      summary: "Persists step results and rollback points into PostgreSQL.",
      kind: "database",
      technology: "PostgreSQL",
      parentId: "workflow-engine",
      evidence: ["services/engine/src/checkpoint.ts"],
      tags: ["postgres", "wal"],
      status: "ready",
    },
  ],
  edges: [
    // Root level topology
    { source: "frontend-portal", target: "auth-guard", label: "bearer token" },
    { source: "auth-guard", target: "api-gateway", label: "authorized session" },
    { source: "api-gateway", target: "event-bus", label: "publish task" },
    { source: "event-bus", target: "workflow-engine", label: "dequeue step" },
    { source: "workflow-engine", target: "ai-synthesizer", label: "invoke LLM" },
    { source: "workflow-engine", target: "primary-db", label: "save state" },
    { source: "workflow-engine", target: "cloud-storage", label: "upload artifact" },
    { source: "primary-db", target: "payment-hub", label: "sync billing" },
    { source: "event-bus", target: "analytics-lake", label: "telemetry stream" },

    // API Gateway Internal Endpoints Flow
    { source: "api-auth-login", target: "auth-guard", label: "verify creds" },
    { source: "api-workflows-create", target: "primary-db", label: "insert workflow" },
    { source: "api-workflows-get", target: "primary-db", label: "query record" },
    { source: "api-workflows-run", target: "event-bus", label: "enqueue stream" },
    { source: "api-ai-synthesize", target: "ai-synthesizer", label: "stream prompt" },
    { source: "api-stripe-webhook", target: "payment-hub", label: "webhook event" },
    { source: "api-graphql", target: "primary-db", label: "resolve query" },

    // Frontend Portal internal flow
    { source: "auth-modal", target: "web-dashboard", label: "authenticated" },
    { source: "web-dashboard", target: "canvas-editor", label: "open graph" },
    { source: "mobile-client", target: "web-dashboard", label: "sync state" },

    // Workflow Engine internal flow
    { source: "dispatch-service", target: "branch-evaluator", label: "eval rules" },
    { source: "branch-evaluator", target: "k8s-runner", label: "schedule container" },
    { source: "k8s-runner", target: "state-checkpoint", label: "write checkpoint" },
  ],
};

export const previewGraph: GeneratedFlowGraph = (() => {
  const graph = parseFlowGraph(source);
  return {
    projectId: "0b6f4d3e-3f2a-4b7c-8d1e-9a0c5f2b7d41",
    provider: "codex",
    snapshotHash: "preview-v2",
    generatedAt: new Date("2026-08-29T00:00:00.000Z").toISOString(),
    graph,
    layout: createDefaultGraphLayout(graph),
    layoutVersion: 2,
  };
})();
