import { createDefaultGraphLayout, parseFlowGraph, type FlowGraph, type GeneratedFlowGraph } from "@insightify/graph-domain";

// A hand-written Graph with diverse architectural node kinds, cloud providers, and nested Portals
const source = {
  title: "Insightify Architecture",
  summary: "Comprehensive FlowFold map with rich architectural nodes and cloud components.",
  nodes: [
    {
      id: "ingest",
      title: "Ingest Watcher",
      summary: "Watch working tree and build sandbox snapshot copy.",
      kind: "service",
      technology: "Docker",
      parentId: null,
      evidence: ["src/main/project-snapshot.ts"],
      tags: ["fs", "watcher", "docker"],
      status: "ready",
      codeSnippet: "export async function captureSnapshot(root: string): Promise<ProjectSnapshot>",
    },
    {
      id: "auth-guard",
      title: "Auth & Permissions",
      summary: "Validate IPC caller and project sandbox privileges.",
      kind: "auth",
      technology: "OAuth",
      parentId: null,
      evidence: ["src/main/ipc.ts"],
      tags: ["security", "guard", "ipc"],
      status: "ready",
      codeSnippet: "export function verifyPrivileges(req: Request): boolean",
    },
    {
      id: "api-gateway",
      title: "GET /graph/:projectId",
      summary: "IPC & Desktop bridge endpoint providing layout and graph documents.",
      kind: "api",
      technology: "REST",
      parentId: null,
      evidence: ["packages/desktop-bridge/src/index.ts"],
      tags: ["api", "bridge", "ipc"],
      status: "ready",
      codeSnippet: "export async function getProjectGraph(id: string): Promise<GeneratedFlowGraph>",
    },
    {
      id: "ai-agent",
      title: "LLM Decomposition",
      summary: "Synthesize FlowFold structure and auto-classify architectural nodes.",
      kind: "external",
      technology: "OpenAI",
      parentId: null,
      evidence: ["packages/agent-codex/src/index.ts"],
      tags: ["llm", "openai", "agent"],
      status: "working",
      codeSnippet: "export async function runDecomposition(prompt: string): Promise<FlowGraph>",
    },
    {
      id: "canvas-ui",
      title: "FlowFold Stage",
      summary: "Render interactive Portal canvas, semantic zoom, and breadcrumbs.",
      kind: "ui",
      technology: "React",
      parentId: null,
      evidence: ["src/renderer/App.tsx"],
      tags: ["ui", "flowfold", "canvas"],
      status: "ready",
      codeSnippet: "export function App(): React.JSX.Element",
    },
    {
      id: "cloud-sync",
      title: "Cloud Backup",
      summary: "Stream repository shadow copies and graph revisions to cloud.",
      kind: "external",
      technology: "AWS",
      parentId: null,
      evidence: ["src/main/cloud-sync.ts"],
      tags: ["aws", "s3", "backup"],
      status: "ready",
      codeSnippet: "export async function syncToS3(projectId: string): Promise<void>",
    },
    {
      id: "job-queue",
      title: "Analysis Queue",
      summary: "Buffer AST parsing and graph balancing jobs asynchronously.",
      kind: "queue",
      technology: "Redis",
      parentId: null,
      evidence: ["src/main/queue.ts"],
      tags: ["redis", "queue", "async"],
      status: "ready",
      codeSnippet: "export const jobQueue = new Queue('graph-tasks', { connection: redis });",
    },
    {
      id: "db-store",
      title: "Project Repository",
      summary: "Persist project metadata, sandboxes, and graph layouts locally.",
      kind: "database",
      technology: "PostgreSQL",
      parentId: null,
      evidence: ["src/main/project-repository.ts"],
      tags: ["postgres", "sqlite", "storage"],
      status: "ready",
      codeSnippet: "export class SqliteProjectRepository implements ProjectRepository",
    },

    // Ingest child nodes
    {
      id: "watch-tree",
      title: "Watch Tree",
      summary: "Observe file changes under the project root.",
      kind: "service",
      parentId: "ingest",
      evidence: ["src/main/watch.ts"],
      tags: ["fs-events"],
      status: "ready",
    },
    {
      id: "read-files",
      title: "Read Files",
      summary: "Read only text files inside the allow list.",
      kind: "service",
      parentId: "ingest",
      evidence: ["src/main/project-snapshot.ts"],
      tags: ["io"],
      status: "ready",
    },
    {
      id: "hash-snapshot",
      title: "Hash Snapshot",
      summary: "Fingerprint the snapshot so stale graphs are detectable.",
      kind: "database",
      parentId: "ingest",
      evidence: ["src/main/project-snapshot.ts"],
      tags: ["crypto", "hash"],
      status: "ready",
    },

    // Canvas UI child nodes
    {
      id: "layout-stage",
      title: "Stage Geometry",
      summary: "Place Portals from the Room-local layout.",
      kind: "service",
      parentId: "canvas-ui",
      evidence: ["src/renderer/App.tsx"],
    },
    {
      id: "draw-edges",
      title: "Flow Connectors",
      summary: "Route flow edges and boundary links.",
      kind: "ui",
      parentId: "canvas-ui",
      evidence: ["src/renderer/App.tsx"],
    },
    {
      id: "paint-portals",
      title: "Portal Cards",
      summary: "Render folds, icons, and badges at the current semantic level.",
      kind: "ui",
      parentId: "canvas-ui",
      evidence: ["src/renderer/styles.css"],
    },
  ],
  edges: [
    { source: "ingest", target: "auth-guard", label: "snapshot ready" },
    { source: "auth-guard", target: "api-gateway", label: "verified" },
    { source: "api-gateway", target: "job-queue", label: "enqueue task" },
    { source: "job-queue", target: "ai-agent", label: "stream prompt" },
    { source: "ai-agent", target: "db-store", label: "persisted graph" },
    { source: "db-store", target: "canvas-ui", label: "load canvas" },
    { source: "db-store", target: "cloud-sync", label: "replicate" },
    { source: "watch-tree", target: "read-files", label: "changed paths" },
    { source: "read-files", target: "hash-snapshot", label: "file text" },
    { source: "layout-stage", target: "draw-edges", label: "positions" },
    { source: "draw-edges", target: "paint-portals", label: "geometry" },
  ],
} satisfies FlowGraph;

export const previewGraph: GeneratedFlowGraph = (() => {
  const graph = parseFlowGraph(source);
  return {
    projectId: "0b6f4d3e-3f2a-4b7c-8d1e-9a0c5f2b7d41",
    provider: "codex",
    snapshotHash: "preview",
    generatedAt: new Date("2026-08-29T00:00:00.000Z").toISOString(),
    graph,
    layout: createDefaultGraphLayout(graph),
    layoutVersion: 2,
  };
})();
